# https://taskfile.dev

version: '3'

tasks:

  build:
    cmds:
      - dune build
    silent: true

  gentest:
    cmds:
      - _build/default/tool/test_gen/test_gen.exe {{.USER_WORKING_DIR}}/test/files/{{.FILE}} {{.NAME}}  > ./test/{{.FILE}}.ml
    deps: [build]

  test:
    cmds:
      - dune runtest {{.CLI_ARGS}}
    silent: true

  promote:
    cmds:
      - dune promote
    desp: [test]
    silent: true
