# https://taskfile.dev

version: '3'

tasks:

  build:
    cmds:
      - dune build
    silent: true

  build-tool:
    cmds:
      - dune build tool
    silent: true

  gentest:
    cmds:
      - _build/default/tool/test_gen/test_gen.exe {{.USER_WORKING_DIR}}/test/files/{{.FILE}} {{.FILE}}  > ./test/{{.FILE}}.ml

  keyword:
    cmds:
      - _build/default/tool/kw_to_sedlex/kw_to_sedlex.exe {{.KW}}

  new-ast:
    cmds:
      - _build/default/tool/gen_tmpl/gen_tmpl.exe {{.CLI_ARGS}}

  test:
    cmds:
      - dune runtest {{.CLI_ARGS}}
    silent: true

  promote:
    cmds:
      - dune promote
    desp: [test]
    silent: true
