select
  timestampadd(sql_tsi_frac_second, 'express', 3)
  ,timestampadd(sql_tsi_second, 'express', 3)
  ,timestampadd(sql_tsi_minute, 'express', 3)
  ,timestampadd(sql_tsi_hour, 'express', 3)
  ,timestampadd(sql_tsi_day, 'express', 3)
  ,timestampadd(sql_tsi_week, 'express', 3)
  ,timestampadd(sql_tsi_month, 'express', 3)
  ,timestampadd(sql_tsi_quarter, 'express', 3)
  ,timestampadd(sql_tsi_year, 'express', 3)

  ,timestampdiff(sql_tsi_frac_second, 'express', 3)
  ,timestampdiff(sql_tsi_second, 'express', 3)
  ,timestampdiff(sql_tsi_minute, 'express', 3)
  ,timestampdiff(sql_tsi_hour, 'express', 3)
  ,timestampdiff(sql_tsi_day, 'express', 3)
  ,timestampdiff(sql_tsi_week, 'express', 3)
  ,timestampdiff(sql_tsi_month, 'express', 3)
  ,timestampdiff(sql_tsi_quarter, 'express', 3)
  ,timestampdiff(sql_tsi_year, 'express', 3)
from a
