select
   left()
  ,left('a', '2')
  ,right()
  ,right('a', '2')
  ,char()
  ,char('a', '2')
  ,user()
  ,user('a', '2')
  ,year()
  ,year('a', '2')
  ,month()
  ,month('a', '2')
  ,hour()
  ,hour('a', '2')
  ,minute()
  ,minute('a', '2')
  ,second()
  ,second('a', '2')
  ,xmlconcat()
  ,xmlconcat('a', '2')
  ,xmlcomment()
  ,xmlcomment('a', '2')
  ,xmltext()
  ,xmltext('a', '2')
from a
