select
 very_looooooooooooooooooooooooooooooooooooong_identifier * very_loooooooooooooooooooooooooooooooooooooooooong / very_loooooooooooooooooooooooooooooooooong +  very_looooooooooooooooooooooooooooooooooooong_identifier * very_loooooooooooooooooooooooooooooooooooooooooong / very_loooooooooooooooooooooooooooooooooong

from a
